resources:
  - name: <GIT_RESOURCE>
    type: GitRepo
    configuration:
      path: <GIT_ORG_AND_REPO>
      gitProvider: <JFROG_PIPELINES_GIT_INTEGRATION>
      buildOn:
        pullRequestCreate: true
      branches:
        include: master
  - name: <BUILD_INFO_RESOURCE>
    type: BuildInfo
    configuration:
      sourceArtifactory: <JFROG_PIPELINES_ARTIFACTORY_INTEGRATION>
      buildName: BUILD-A
      buildNumber: $run_number
pipelines:
  - name: <JFROG_PIPELINE_NAME>
    configuration:
      environmentVariables:
        readOnly:
          CI: "true"
          JFROG_CLI_BUILD_NAME: BUILD-A
          JFROG_CLI_BUILD_NUMBER: $run_number
          JFROG_CLI_BUILD_URL: $step_url
    steps:
      - name: Build
        type: GradleBuild
        configuration:
          gradleCommand: artifactoryPublish
          resolverRepo: <ARTIFACTORY_REPOSITORY>
          deployerRepo: <ARTIFACTORY_REPOSITORY>
          useWrapper: "true"
          environmentVariables:
            JFROG_BUILD_STATUS: PASS
          integrations:
            - name: <JFROG_PIPELINES_ARTIFACTORY_INTEGRATION>
          inputResources:
            - name: <GIT_RESOURCE>
        execution:
          onFailure:
            - export JFROG_BUILD_STATUS=FAIL
            - jfrog rt bce
            - jfrog rt bag
            - jfrog rt bp
      - name: PublishBuildInfoStep
        type: PublishBuildInfo
        configuration:
          inputResources:
            - name: <GIT_RESOURCE>
          outputResources:
            - name: <BUILD_INFO_RESOURCE>
          inputSteps:
            - name: Build
          forceXrayScan: true
        execution:
          onComplete:
            - update_commit_status <GIT_RESOURCE>
