image: releases-docker.jfrog.io/jfrog/jfrog-cli-full:latest

before_script:
  # Configure Artifactory instance
  - jfrog config add rt --artifactory-url <ARTIFACTORY_URL> --user $JFROG_USERNAME --password $JFROG_PASSWORD --interactive=false
  # Configure Artifactory repository
  - jfrog rt npmc --server-id rt --repo-resolve <ARTIFACTORY_REPOSITORY>

variables:
  RT_BUILD_NAME: "BUILD-A"

cache:
  paths:
    - node_modules/

build:
  script:
    # Run the npm install command
    - jfrog rt npmi --build-name RT_BUILD_NAME --build-number $CI_JOB_ID
    # Add the environment variables to the build-info
    - jfrog rt bce $RT_BUILD_NAME $CI_JOB_ID
    # Add the git details to the build-info
    - jfrog rt bag $RT_BUILD_NAME $CI_JOB_ID
    # Publish the package
    - jfrog rt npmp --build-name $RT_BUILD_NAME --build-number $CI_JOB_ID
    # Publish the build-info to Artifactory
    - jfrog rt bp $RT_BUILD_NAME $CI_JOB_ID
  only:
    - master